server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password123!
    url: jdbc:mysql://localhost:3306/claims
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000