server:
  port: 9080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  auth:
    converter:
      resource-id: movies-app
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password123!
    url: jdbc:mysql://localhost:3306/aicm
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8180/realms/aicm2
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.security: DEBUG
