server:
  port: 9080
  error:
    include-message: always
    include-binding-errors: always

app:
  jwtSecret: secretkey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password123!
    url: jdbc:mysql://localhost:3306/aicm
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true


  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000